### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by Moody66** [manniefesto/neptune-2-firmware#11]
Has this been flashed and known working?

**Comment by Kyrillian** [comment]
I just yolo'd it and flashed the firmware as per the instructions @manniefesto provided.
Everything working as intended.

**Comment by manniefesto** [comment]
> Has this been flashed and known working?

Hi, this is working great on my printer. Just be sure you have the 1.0.3 version.

I'm looking at getting a build ready for the newer version.
