### ISSUE TITLE
Getting a couple errors compiling

### ISSUE THREAD

**Issue by RickzFPV** [manniefesto/neptune-2-firmware#12]
Trey I am trying to build the 2.0.95 for my elegoo printers both have BL touch keep geeting 2 issues.  First one is the ENDIF in the Stepper Drivers section I need to undefine the E1 if I dont have a 2D correct.  The other one is the if and else in the endstop inverting section it is already set to false for the Z min endstop.  So not sure why I am getting these errors I really want to get this firmware built.  Thank you in advance for any light you may be able to shed on this

Rick

**Comment by manniefesto** [comment]
Hi Rick, I would suggest having a look through the Marlin documentation to try and understand these issues. You might also try the Marlin discord.

Thanks!
